import os
import sys
import subprocess
import argparse

def main():
    parser = argparse.ArgumentParser(description="PortSync End-to-End QA Execution")
    parser.add_argument("--module", type=str, help="Specific module to run (e.g. tests/api/)", default="tests/")
    parser.add_argument("--headful", action="store_true", help="Run Playwright E2E tests in visible browser")
    args = parser.parse_args()

    print("=" * 60)
    print("=> PortSync QA Automation Execution Started")
    print("=" * 60)

    # Set up environment variables
    env = os.environ.copy()
    env["PYTHONPATH"] = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    
    # Base pytest command for API tests
    api_cmd = [
        sys.executable, "-m", "pytest",
        "tests/", "--ignore=tests/frontend",
        "-v",
        "--disable-warnings"
    ]
    
    # Base pytest command for E2E tests
    e2e_cmd = [
        sys.executable, "-m", "pytest",
        "tests/frontend/",
        "-v",
        "--disable-warnings"
    ]
    
    if args.headful:
        e2e_cmd.append("--headed")

    # Execute API tests
    print(f"Running API Tests: {' '.join(api_cmd)}\n")
    try:
        result_api = subprocess.run(api_cmd, env=env)
        
        print("\n" + "=" * 60)
        print(f"Running E2E Tests: {' '.join(e2e_cmd)}\n")
        result_e2e = subprocess.run(e2e_cmd, env=env)
        
        print("\n" + "=" * 60)
        if result_api.returncode == 0 and result_e2e.returncode == 0:
            print("[SUCCESS] All tests passed successfully!")
        else:
            print("[FAILED] Some tests failed. Check the generated reports.")
        print("=" * 60)
        
        # Reports are automatically generated by the hooks in conftest.py
        print("\nReports have been generated in tests/reports/")
        
        if result_api.returncode != 0 or result_e2e.returncode != 0:
            sys.exit(1)
            
    except KeyboardInterrupt:
        print("\nTest execution interrupted by user.")
        sys.exit(1)

if __name__ == "__main__":
    main()
